name: Validate Pull Requests

on:
  pull_request:
    branches:
      - main # Ensures this runs only for PRs targeting the `main` branch

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }} # Check out the source branch for validation

      - name: Validate PR Title and Description
        run: |
          echo "Validating PR title and description..."
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_BODY="${{ github.event.pull_request.body }}"
          echo "Title: $PR_TITLE"
          echo "Body: $PR_BODY"

          # Add your validation logic here
          if [[ ! "$PR_TITLE" =~ ^[a-z]+(\([a-z]+\))?:\ .+ ]]; then
            echo "Invalid PR title format."
            exit 1
          fi
          echo "PR title format is valid."


# name: Pull Request Validation

# on:
#   pull_request:
#     branches:
#       - main
#     types: [opened, synchronize, reopened]

# jobs:
#   validate-pr:
#     runs-on: ubuntu-latest

#     steps:
#       # Step 1: Checkout the repository
#       - name: Checkout code
#         uses: actions/checkout@v3

#       # Step 2: Set up GitHub Token (needed to interact with the GitHub API)
#       - name: Set up GitHub Token
#         run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

#       # Step 3: Install jq (required for parsing JSON)
#       - name: Install jq
#         run: sudo apt-get install jq

#       # Step 4: Make the validation script executable
#       - name: Make validation script executable
#         run: chmod +x ./.github/scripts/validate-pr

#       # Step 5: Run the PR validation script
#       - name: Validate PR Title, Body, and Footer
#         run: |
#           # PR details: fetch from GitHub API
#           PR_NUMBER=${{ github.event.pull_request.number }}
#           REPO_OWNER=${{ github.repository_owner }}
#           REPO_NAME=${{ github.repository }}
#           GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

#           # Run your PR validation script
#           ./.github/scripts/validate-pr "$PR_NUMBER" "$REPO_OWNER" "$REPO_NAME" "$GITHUB_TOKEN"
