name: Pull Request Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up GitHub Token (needed to interact with the GitHub API)
      - name: Set up GitHub Token
        run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      # Step 3: Install jq (required for parsing JSON)
      - name: Install jq
        run: sudo apt-get install jq

      # Step 4: Make the validation script executable
      - name: Make validation script executable
        run: chmod +x ./.github/scripts/validate-pr

      # Step 5: Run the PR validation script
      - name: Validate PR Title, Body, and Footer
        run: |
          # PR details: fetch from GitHub API
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO_OWNER=${{ github.repository_owner }}
          REPO_NAME=${{ github.repository }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          # Run your PR validation script
          ./.github/scripts/validate-pr "$PR_NUMBER" "$REPO_OWNER" "$REPO_NAME" "$GITHUB_TOKEN"