name: Validate Commit Message and Check GitHub Actions Changes

on:
  push:
    branches:
      - '**'  # Runs for all branches when a commit is pushed
  pull_request:
    branches:
      - main  # Runs when a pull request is created targeting the 'main' branch

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch the commit message from GitHub context
      - name: Fetch commit message
        id: commit_message
        run: echo "COMMIT_MSG=${{ github.event.head_commit.message }}" >> $GITHUB_ENV

      # Step 3: Validate commit message
      - name: Validate commit message format
        run: |
          # Use the script to validate the commit message
          echo "$COMMIT_MSG" > commit-msg.txt
          chmod +x .github/scripts/commit-msg
          ./.github/scripts/commit-msg commit-msg.txt

  check-github-actions:
    runs-on: ubuntu-latest
    needs: validate-commit-message
    if: github.event_name == 'pull_request'  # Run only on pull requests to main

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch the base branch (main) version of the GitHub Actions workflow
      - name: Fetch base branch (main)
        run: |
          git fetch origin main

      # Step 3: Compare GitHub Actions workflow files
      - name: Compare GitHub Actions workflows
        run: |
          # Compare .github/workflows/*.yml files
          DIFF=$(git diff origin/main -- .github/workflows/)

          if [ -n "$DIFF" ]; then
            echo "❌ ERROR: GitHub Actions workflow files have changed!"
            echo "The following differences were found:"
            echo "$DIFF"
            exit 1
          else
            echo "✅ SUCCESS: No changes detected in GitHub Actions workflow files."
          fi