name: Validate Commit Message and Check GitHub Actions Changes

on:
  push:
    branches:
      - '**'  # Runs for all branches when a commit is pushed
  pull_request:
    branches:
      - main  # Runs when a pull request is created targeting the 'main' branch
      
jobs:
  validate-commit-message:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Fetch the commit message
      - name: Fetch commit message
        run: |
          # Fetch the commit message of the last commit
          COMMIT_MSG=$(git log -1 --pretty=format:"%B")
          echo "Commit Message: $COMMIT_MSG"
          
          # Write the commit message to commit-msg.txt
          echo "$COMMIT_MSG" > commit-msg.txt

      # Step 3: Print the contents of commit-msg.txt for debugging
      - name: Print commit-msg.txt contents
        run: |
          echo "Printing commit-msg.txt contents:"
          cat commit-msg.txt

      # Step 4: Run the commit-msg validation script
      - name: Run commit-msg script
        run: |
          # Make the commit-msg script executable
          chmod +x .github/scripts/commit-msg
          
          # Run the commit-msg script to validate the message
          ./.github/scripts/commit-msg commit-msg.txt



    

  check-github-actions:
    runs-on: ubuntu-latest
    needs: validate-commit-message
    if: github.event_name == 'pull_request'  # Run only on pull requests to main

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch the base branch (main) version of the GitHub Actions workflow
      - name: Fetch base branch (main)
        run: |
          git fetch origin main

      # Step 3: Compare GitHub Actions workflow files
      - name: Compare GitHub Actions workflows
        run: |
          # Compare .github/workflows/*.yml files
          DIFF=$(git diff origin/main -- .github/workflows/)

          if [ -n "$DIFF" ]; then
            echo "❌ ERROR: GitHub Actions workflow files have changed!"
            echo "The following differences were found:"
            echo "$DIFF"
            exit 1
          else
            echo "✅ SUCCESS: No changes detected in GitHub Actions workflow files."
          fi